config/routes.rb
Jobapp::Application.routes.draw do

  resources :headers

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :accounts
  devise_for :users

  resources :companies do
    resources :reasons,  only: [:edit, :update]
    resources :uploads
    resources :headers
  end
  
  resources :addresses
  resources :missions, only: [:edit, :update] 
  resources :accounts, only: [:show]
  resources :users, only: [:index, :show]
  root to: "static_pages#welcome"
  match '/pro_access' => 'static_pages#pro', :as => 'pro_access', via: 'get'

  

  

end

app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/address.rb
class Address < ActiveRecord::Base
	acts_as_gmappable
	
	belongs_to :addressable, polymorphic: true
	validates :country, presence: true
	validates :city, presence: true
	validates :zip, presence: true
	validates :street, presence: true

	def gmaps4rails_address
	#describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
	  "#{self.street}, #{self.city}, #{self.country}" 
	end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_and_belongs_to_many :accounts
	validates :name, presence: true, length: { maximum: 50 }
	validates :teaser, presence: true, length: { maximum: 400 }
	has_one :address, as: :addressable
	#addressable because polymorphic (can be used by multiple models)
	
	has_one :mission, dependent: :destroy
	has_one :reason, dependent: :destroy
	has_many :uploads, dependent: :destroy
	has_many :headers, dependent: :destroy

	accepts_nested_attributes_for :address

	has_attached_file :logo,
                  url: "/assets/companies/:id/:style/:basename.:extension",
                  path: ":rails_root/public/assets/companies/:id/:style/:basename.:extension"

	validates_attachment_presence :logo
	validates_attachment_size :logo, less_than: 3.megabytes
	validates_attachment_content_type :logo, content_type: ['image/jpeg', 'image/png']
end

app/models/header.rb
class Header < ActiveRecord::Base
	belongs_to :company


	has_attached_file :image, styles: { carousel: "1150x450#" },
              url: "/assets/companies/:id/:style/:basename.:extension",
              path: ":rails_root/public/assets/companies/:id/:style/:basename.:extension"

	validates_attachment_presence :image
	validates_attachment_size :image, less_than: 4.megabytes
	validates_attachment_content_type :image, content_type: ['image/jpeg', 'image/png']
end

app/models/mission.rb
class Mission < ActiveRecord::Base
	belongs_to :company
	validates :statement, presence: true, length: {maximum: 180}
	validates :impact, presence: true, length: {maximum: 180}
end

app/models/reason.rb
class Reason < ActiveRecord::Base
	belongs_to :company
	validates :why1, presence: true, length: {maximum: 180}
	validates :why2, presence: true, length: {maximum: 180}
	validates :why3, presence: true, length: {maximum: 180}
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	belongs_to :company

	has_attached_file :photo
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
  		@companies = Company.all
  		@map = Address.all.to_gmaps4rails
  end

  def pro
  	
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/headers_helper.rb
module HeadersHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/reasons_helper.rb
module ReasonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/pro.html.erb
<% provide(:title, 'Pro Access') %>

<div class="center hero-unit">

<h1>Pro Access</h1>
<p>Start mediatizing your company to the right candidates now.</p>
<p>You are just a few clicks away ...</p>

<%= link_to "Register now", new_account_registration_path, class: "btn btn-large btn-primary" %> or 
<%= link_to "Log In", new_account_session_path, class: "btn btn-large btn-primary" %>


</div>


<div class="row">
<div class="span6 offset3">
	<div class="progress progress-striped active">
  	<div class="bar" style="width: 33%;"></div>
	</div>
</div>
</div>

app/views/static_pages/welcome.html.erb
<% provide(:title, 'Home') %>



<% if account_signed_in? %>
	<div class="row">
	<div class="span6 offset3">
		<% @companies.each do |company| %>
			<h4><%= company.name %></h4>
			<p><%= company.teaser %></p>
		<% end %>
	</div>
	</div>	
	<%= gmaps({
	  "map_options" => {"auto_zoom" => false, "zoom" => 2 },
	  "markers"     => {"data" => @map }
	 })
	%>
<% else %>
	<div class="jumbotron masthead">
		<div class="container">
			<h1>JobParadize.com</h1>
			<p>The best jobs in the best cities around - in a way you've never seen before.</p>
			<p>Launching soon, sign up for updates !</p>
			<br>
			<%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
		</div>
	</div>

	<div class="container">
		<div class="marketing">
			<h1>Welcome to Job Paradize !</h1>
			<p class="marketing-byline">Your dream job has never been that close...</p>
		

			<div class="row-fluid">
				<div class="span4">
					<%= image_tag "https://cdn1.iconfinder.com/data/icons/PRACTIKA/256/job_openings.png", class:"marketing-img" %>
					<h2>Explore jobs in our cities</h2>
					<p>We have selected the companies that offer the best experiences, in some of the most vibrant cities around.</p>
				</div>
				<div class="span4">
					<%= image_tag "https://cdn1.iconfinder.com/data/icons/PRACTIKA/256/job_openings.png", class:"marketing-img" %>
					<h2>Explore jobs in our cities</h2>
					<p>We have selected the companies that offer the best experiences, in some of the most vibrant cities around.</p>
				</div>
				<div class="span4">
					<%= image_tag "https://cdn1.iconfinder.com/data/icons/PRACTIKA/256/job_openings.png", class:"marketing-img" %>
					<h2>Explore jobs in our cities</h2>
					<p>We have selected the companies that offer the best experiences, in some of the most vibrant cities around.</p>
				</div>
			</div>
		</div>
	</div>
<% end %>