config/routes.rb
Jobapp::Application.routes.draw do

  resources :headers

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :accounts
  devise_for :users

  resources :companies do
    resources :reasons,  only: [:edit, :update]
    resources :uploads
    resources :headers
  end
  
  resources :addresses
  resources :missions, only: [:edit, :update] 
  resources :accounts, only: [:show]
  resources :users, only: [:index, :show]
  root to: "static_pages#welcome"
  match '/pro_access' => 'static_pages#pro', :as => 'pro_access', via: 'get'

  

  

end

app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/address.rb
class Address < ActiveRecord::Base
	acts_as_gmappable
	
	belongs_to :addressable, polymorphic: true
	validates :country, presence: true
	validates :city, presence: true
	validates :zip, presence: true
	validates :street, presence: true

	def gmaps4rails_address
	#describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
	  "#{self.street}, #{self.city}, #{self.country}" 
	end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_and_belongs_to_many :accounts
	validates :name, presence: true, length: { maximum: 50 }
	validates :teaser, presence: true, length: { maximum: 400 }
	has_one :address, as: :addressable
	#addressable because polymorphic (can be used by multiple models)
	
	has_one :mission, dependent: :destroy
	has_one :reason, dependent: :destroy
	has_many :uploads, dependent: :destroy
	has_many :headers, dependent: :destroy

	accepts_nested_attributes_for :address

	has_attached_file :logo,
                  url: "/assets/companies/:id/:style/:basename.:extension",
                  path: ":rails_root/public/assets/companies/:id/:style/:basename.:extension"

	validates_attachment_presence :logo
	validates_attachment_size :logo, less_than: 3.megabytes
	validates_attachment_content_type :logo, content_type: ['image/jpeg', 'image/png']
end

app/models/header.rb
class Header < ActiveRecord::Base
	belongs_to :company


	has_attached_file :image, styles: { carousel: "1150x450#" },
              url: "/assets/companies/:id/:style/:basename.:extension",
              path: ":rails_root/public/assets/companies/:id/:style/:basename.:extension"

	validates_attachment_presence :image
	validates_attachment_size :image, less_than: 4.megabytes
	validates_attachment_content_type :image, content_type: ['image/jpeg', 'image/png']
end

app/models/mission.rb
class Mission < ActiveRecord::Base
	belongs_to :company
	validates :statement, presence: true, length: {maximum: 180}
	validates :impact, presence: true, length: {maximum: 180}
end

app/models/reason.rb
class Reason < ActiveRecord::Base
	belongs_to :company
	validates :why1, presence: true, length: {maximum: 180}
	validates :why2, presence: true, length: {maximum: 180}
	validates :why3, presence: true, length: {maximum: 180}
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	belongs_to :company

	has_attached_file :photo
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_filter :authenticate_account!
	#before_filter :correct_account


	def new
		@account = current_account
		@company = Company.new
		@company.build_address
	end

	def create
		@account = current_account
		@company = Company.new(company_params)
		if @company.accounts<<@account && @company.save
			@company.create_mission(statement: "Dummy statement", impact: "Dummy impact")
			@company.create_reason(why1: "You should come because...", why2: "You should come because...", why3: "You should come because...")
			flash[:success] = "Company created!"
			redirect_to current_account
		else
			render 'new'
		end	
	end

	def show
		@company = current_account.companies.find(params[:id])
		@mission = @company.mission
		@reason  = @company.reason
		@json = @company.address.to_gmaps4rails
		@headers = @company.headers.all
	end

	def edit
		@company = Company.find(params[:id])
	end

	def update
		@company = Company.find(params[:id])
		if @company.update_attributes(company_params)
			flash[:success] = "Update successful!"
			redirect_to current_account
		else
			render 'edit'
		end		
	end

	def destroy
		current_account.companies.find(params[:id]).destroy
		flash[:success] = "Company Destroyed"
		redirect_to current_account
	end

	private

	  def company_params
	    params.require(:company).permit(:name, :teaser, :logo, address_attributes: [:country, :city, :zip, :street])
	    #integrates the nested attributes for address that are posted when company gets posted.
	  end

	  def correct_account
	  	@company = current_account.companies.find_by(id: params[:id])
	  	redirect_to root_url if @company.nil?
	  	#we use find_by instead of find because the latter raises an exception when the micropost doesn’t exist instead of returning nil
	  	#is there inside current_account.companies on with the ID of the params ? if yes ok, if nil then redirect
	  end  


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!

	def index
	@users = User.all
	end

	def show
	@user = User.find(params[:id])
	end	

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/headers_helper.rb
module HeadersHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/reasons_helper.rb
module ReasonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/edit.html.erb
<h1>Update your Company</h1>

<div class="row">
<div class="span6 offset3">


<%= form_for @company, html: { multipart: true } do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, :autofocus => true %>

  <%= f.file_field :logo %>

  <%= f.label :teaser %>
  <%= f.text_area :teaser %>

  <%= f.fields_for :address do |address| %>
  	<%= render 'shared/address', f: address %>
  <% end %>  

  <%= f.submit "Update", class: "btn btn-large btn-primary" %>
<% end %>

</div>
</div>

app/views/companies/new.html.erb
<h1>Register a New Company</h1>

<div class="row">
<div class="span6 offset3">

<%= form_for @company, html: { multipart: true } do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, :autofocus => true %>

  <%= f.file_field :logo %>

  <%= f.label :teaser %>
  <%= f.text_area :teaser %>

  <%= f.fields_for :address do |address| %>
  	<%= render 'shared/address', f: address %>
  <% end %>

  <%= f.submit "Create Company", class: "btn btn-large btn-primary" %>
<% end %>

</div>
</div>

app/views/companies/show.html.erb
<div id="company-carousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#company-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#company-carousel" data-slide-to="1"></li>
  </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">

    	<div class="item active">
    	<%= image_tag @headers.first.image.url(:carousel) %>
    	<div class="carousel-caption">
			<h1><%= @headers.first.title %></h1>
			<p class="lead"><%= @headers.first.caption %> <small class="edit-button"><%= link_to "Edit", company_headers_path(@company) %></small></p>
		</div>
    	</div>

    	<% @headers.drop(1).each do |header| %>
	    	<div class="item">
    		<%= image_tag header.image.url(:carousel) %>
    		<div class="carousel-caption">
    			<h1><%= header.title %></h1>
    			<p class="lead"><%= header.caption %> <small class="edit-button"><%= link_to "Edit", company_headers_path(@company) %></small></p>
			</div>
    		</div>
    	<% end %>

    </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#company-carousel" data-slide="prev">
    <span class="icon-prev">‹</span>
  </a>
  <a class="right carousel-control" href="#company-carousel" data-slide="next">
    <span class="icon-next">›</span>
  </a>
</div>



<div class="container-fluid">

	<div class="container">
		<% flash.each do |key, value| %>
	    <div class="alert alert-<%= key %>"><%= value %></div>
	  	<% end %>
  	</div> 

	<div class="row-fluid">	
		<div class="span3 offset1">
			<div class="box-complete">
				<%= image_tag @company.logo.url %>
				<hr class="soften">
				<h1><%= @company.name %> is :</h1>
				<p><%= @company.teaser %> <small class="edit-button"><%= link_to "Edit", edit_company_path(@company)  %></small></p>
				<hr class="soften">
				<%= gmaps({
				  "map_options" => {"auto_zoom" => false, "zoom" => 14 },
				  "markers"     => {"data" => @json }
				 })
				%>
			</div>				
		</div>	

		<div class="span7">
			<div class="box-head">
				<h3>Mission Statement & Impact <small class="edit-button"><%= link_to "Edit", edit_mission_path(@mission)  %></small></h3>
			</div>
			<div class="box-main">	
					<p><%= @company.mission.statement %></p>
					<p><%= @company.mission.impact %></p>
			</div>
		

			<div class="box-head">
				<h3>3 Reasons you should join us <small class="edit-button"><%= link_to "Edit", edit_company_reason_path(@company, @reason)  %></small></h3>
			</div>
			<div class="box-main">	
				<p><%= @company.reason.why1 %></p>
				<p><%= @company.reason.why2 %></p>
				<p><%= @company.reason.why3 %></p>
			</div>

			<div class="box-head">
				<h3>Check out our pictures <small class="edit-button"><%= link_to "Edit", company_uploads_path(@company) %></small></h3>
			</div>

			<div class="box-main album">	
				<% @company.uploads.each do |upload| %>
					<%= image_tag upload.photo.url %>
				<% end %>
			</div>

		</div>
	</div>

	<div class="container">
		<br><%= link_to "Delete your company", @company, method: :delete, data: {confirm: "Are you sure ?"}, title: @company.teaser %>
	</div>
</div>

<script>
	$(document).ready(function() {
		$('.carousel').carousel({
		  interval: 7000
		});
	});
</script>