config/routes.rb
Jobapp::Application.routes.draw do

  resources :headers

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :accounts
  devise_for :users

  resources :companies do
    resources :reasons,  only: [:edit, :update]
    resources :uploads
    resources :headers
  end
  
  resources :addresses
  resources :missions, only: [:edit, :update] 
  resources :accounts, only: [:show]
  resources :users, only: [:index, :show]
  root to: "static_pages#welcome"
  match '/pro_access' => 'static_pages#pro', :as => 'pro_access', via: 'get'

  

  

end

app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/address.rb
class Address < ActiveRecord::Base
	acts_as_gmappable
	
	belongs_to :addressable, polymorphic: true
	validates :country, presence: true
	validates :city, presence: true
	validates :zip, presence: true
	validates :street, presence: true

	def gmaps4rails_address
	#describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
	  "#{self.street}, #{self.city}, #{self.country}" 
	end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_and_belongs_to_many :accounts
	validates :name, presence: true, length: { maximum: 50 }
	validates :teaser, presence: true, length: { maximum: 400 }
	has_one :address, as: :addressable
	#addressable because polymorphic (can be used by multiple models)
	
	has_one :mission, dependent: :destroy
	has_one :reason, dependent: :destroy
	has_many :uploads, dependent: :destroy
	has_many :headers, dependent: :destroy

	accepts_nested_attributes_for :address

	has_attached_file :logo,
                  url: "/assets/companies/:id/:style/:basename.:extension",
                  path: ":rails_root/public/assets/companies/:id/:style/:basename.:extension"

	validates_attachment_presence :logo
	validates_attachment_size :logo, less_than: 3.megabytes
	validates_attachment_content_type :logo, content_type: ['image/jpeg', 'image/png']
end

app/models/header.rb
class Header < ActiveRecord::Base
	belongs_to :company


	has_attached_file :image, styles: { carousel: "1150x450#" },
              url: "/assets/companies/:id/:style/:basename.:extension",
              path: ":rails_root/public/assets/companies/:id/:style/:basename.:extension"

	validates_attachment_presence :image
	validates_attachment_size :image, less_than: 4.megabytes
	validates_attachment_content_type :image, content_type: ['image/jpeg', 'image/png']
end

app/models/mission.rb
class Mission < ActiveRecord::Base
	belongs_to :company
	validates :statement, presence: true, length: {maximum: 180}
	validates :impact, presence: true, length: {maximum: 180}
end

app/models/reason.rb
class Reason < ActiveRecord::Base
	belongs_to :company
	validates :why1, presence: true, length: {maximum: 180}
	validates :why2, presence: true, length: {maximum: 180}
	validates :why3, presence: true, length: {maximum: 180}
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	belongs_to :company

	has_attached_file :photo
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload,  only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @company = Company.find(params[:company_id])
    @uploads = @company.uploads.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @company = Company.find(params[:company_id])
    @upload = @company.uploads.build
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @company = Company.find(params[:company_id])
    @upload = @company.uploads.build(upload_params)

    respond_to do |format|
      if @upload.save
        format.html { render action: 'show', notice: 'Upload was successfully created.' }
        format.json { render action: 'show', status: :created, location: @upload }
      else
        format.html { render action: 'new' }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { render action: 'show', notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to company_uploads_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @company = Company.find(params[:company_id])
      @upload = @company.uploads.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:title, :caption, :photo)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!

	def index
	@users = User.all
	end

	def show
	@user = User.find(params[:id])
	end	

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/headers_helper.rb
module HeadersHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/reasons_helper.rb
module ReasonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/uploads/_form.html.erb
<%= form_for([@company, @upload], html: { multipart: true }) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :caption %><br>
    <%= f.text_area :caption %>
  </div>

  <p>
    <%= f.file_field :photo %>
  </p>

  <div class="actions">
    <%= f.submit class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', company_upload_path(@company, @upload) %> |
<%= link_to 'Back', company_uploads_path %>

app/views/uploads/index.html.erb
<h1>Listing uploads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Caption</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= upload.title %></td>
        <td><%= upload.caption %></td>
        <td><%= link_to 'Show', [@company, upload] %></td>
        <td><%= link_to 'Edit', edit_company_upload_path(@company, upload) %></td>
        <td><%= link_to 'Destroy', [@company, upload], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upload', new_company_upload_path %>

app/views/uploads/new.html.erb
<h1>New upload</h1>

<%= render 'form' %>

<%= link_to 'Back', company_uploads_path %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @upload.photo.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @upload.title %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @upload.caption %>
</p>

<%= link_to 'Edit', edit_company_upload_path(@company, @upload) %> |
<%= link_to 'Back', company_uploads_path %>